version: "3.8"

services:
  app:
    build: .
    container_name: iffservices
    command: hypercorn main:app --bind 0.0.0.0:5001 --reload
    ports:
      - "5001:5001"
    environment:
      MONGO_URI: mongodb://mongodb:27017/
      MONGO_DB_NAME: communities_db
      JWT_SECRET: 42a6A#8epiwj?A:R?DqCKpn5f
      JWT_ALGORITHM: HS256
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DB: 0
      # REDIS_PASSWORD: mypassword  # uncomment if Redis auth is enabled
    depends_on:
      - mongodb
      - redis

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:7.2
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    # command: ["redis-server", "--requirepass", "mypassword"] # uncomment if you want password auth
    volumes:
      - redis_data:/data

volumes:
  mongodb_data:
  redis_data: